package com.example.moum.utils;

public enum Validation {

    /*FRONTEND 고유 에러 LIST*/

    //NOT WRITTEN
    ID_NOT_WRITTEN,
    PASSWORD_NOT_WRITTEN,
    PASSWORD_CHECK_NOT_WRITTEN,
    EMAIL_NOT_WRITTEN,
    EMAIL_CODE_NOT_WRITTEN,
    NICKNAME_NOT_WRITTEN,
    INSTRUMENT_NOT_WRITTEN,
    PROFICIENCY_NOT_WRITTEN,
    TEAM_NAME_NOT_WRITTEN,
    TEAM_GENRE_NOT_WRITTEN,
    MOUM_NAME_NOT_WRITTEN,

    //NOT FORMAL
    ID_NOT_FORMAL,
    PASSWORD_NOT_FORMAL,
    EMAIL_NOT_FORMAL,
    EMAIL_CODE_NOT_FORMAL,
    PASSWORD_NOT_EQUAL,

    //개인정보 동의
    PERSONAL_NOT_AGREE,

    //회원가입
    BASIC_SIGNUP_NOT_TRIED,

    // 채팅방
    CHATROOM_NOT_LOADED,
    CHATROOM_NAME_EMPTY,
    PARTICIPATE_AT_LEAST_TWO,
    GROUP_NOT_SELECTED,
    CHATROOM_CREATE_SUCCESS,
    CHATROOM_CREATE_FAIL,
    CHATROOM_MEMBER_LOAD_SUCCESS,
    CHATROOM_ALREADY_EXIST,
    CHATROOM_WITH_ME,

    // 팀

    // 프로필
    PROFILE_NOT_LOADED,

    //이외 에러 처리
    NOT_VALID_ANYWAY,
    NETWORK_FAILED,
    VALID_ALL,


    /*BACKEND 에러 LIST*/

    // 이메일 인증
    EMAIL_AUTH_SUCCESS,
    EMAIL_AUTH_FAILED,
    EMAIL_AUTH_ALREADY,
    EMAIL_AUTH_NOT_TRIED,

    // 회원가입
    SIGNUP_SUCCESS,

    // 로그인 및 로그아웃
    LOGIN_SUCCESS,
    LOGOUT_SUCCESS,
    LOGIN_FAILED,
    LOGOUT_ALREADY,

    // 채팅
    CHAT_POST_SUCCESS,
    CHAT_POST_FAIL,
    CHAT_RECEIVE_SUCCESS,
    CHAT_RECEIVE_FAIL,

    // 멤버 관련 성공 응답
    REISSUE_SUCCESS,
    GET_MY_INFO_SUCCESS,

    // 팀 관련 성공 응답
    CREATE_TEAM_SUCCESS,
    UPDATE_TEAM_SUCCESS,
    DELETE_TEAM_SUCCESS,
    GET_TEAM_SUCCESS,
    GET_TEAM_LIST_SUCCESS,
    GET_MY_TEAM_LIST_SUCCESS,
    INVITE_MEMBER_SUCCESS,
    KICK_MEMBER_SUCCESS,
    LEAVE_TEAM_SUCCESS,

    // 게시글 관련 성공 응답
    ARTICLE_LIST_GET_SUCCESS,
    ARTICLE_GET_SUCCESS,
    ARTICLE_POST_SUCCESS,
    ARTICLE_UPDATE_SUCCESS,
    ARTICLE_DELETE_SUCCESS,

    // JWT 관련 성공 응답
    ACCESS_TOKEN_ISSUE_SUCCESS,

    // 댓글 관련 성공 응답
    COMMENT_CREATE_SUCCESS,
    COMMENT_UPDATE_SUCCESS,
    COMMENT_DELETE_SUCCESS,

    // 좋아요 관련 성공 응답
    LIKES_CREATE_SUCCESS,
    LIKES_DELETE_SUCCESS,

    // 이력 관련 성공 응답
    RECORD_ADD_SUCCESS,
    RECORD_DELETE_SUCCESS,
    RECORD_GET_SUCCESS,
    RECORD_LIST_GET_SUCCESS,

    // 프로필 관련 성공 응답
    GET_PROFILE_SUCCESS,
    UPDATE_PROFILE_SUCCESS,

    // 모음 관련 성공 응답
    CREATE_MOUM_SUCCESS,
    GET_MOUM_SUCCESS,
    UPDATE_MOUM_SUCCESS,
    DELETE_MOUM_SUCCESS,
    FINISH_MOUM_SUCCESS,
    REOPEN_MOUM_SUCCESS,

    // 공통 오류 코드
    INTERNAL_SERVER_ERROR,
    INVALID_INPUT_VALUE,
    METHOD_NOT_ALLOWED,
    INVALID_TYPE_VALUE,
    BAD_CREDENTIALS,
    ILLEGAL_ARGUMENT,

    // 멤버 관련 오류 코드
    MEMBER_NOT_EXIST,
    USER_NAME_ALREADY_EXISTS,
    NO_AUTHORITY,
    NEED_LOGIN,
    AUTHENTICATION_NOT_FOUND,
    MEMBER_ALREADY_LOGOUT,

    // 인증 관련 오류 코드
    LOGIN_FAIL,
    REFRESH_TOKEN_INVALID,
    JWT_TOKEN_EXPIRED,

    // 게시글 관련 오류 코드
    ARTICLE_NOT_FOUND,
    ARTICLE_ALREADY_DELETED,

    // 위시리스트 관련 오류 코드
    ALREADY_IN_WISHLIST,
    ALREADY_DELETED_WISHLIST,

    // 댓글 관련 오류 코드
    COMMENT_NOT_FOUND,
    COMMENT_ALREADY_DELETED,

    // 좋아요 관련 오류 코드
    DUPLICATE_LIKES,
    LIKES_NOT_FOUND,
    CANNOT_CREATE_SELF_LIKES,
    CANNOT_DELETE_OTHERS_LIKES,

    // 팀 관련 오류 코드
    MEMBER_ALREADY_INVITED,
    TEAM_NOT_FOUND,
    NOT_TEAM_MEMBER,
    LEADER_CANNOT_LEAVE,
    MUST_JOIN_TEAM_FIRST

    }