name: Build and Release

on:
  pull_request:
    types: [closed]  # PR이 닫히는 이벤트(merged 포함)에 대해서만 실행
    branches:
      - main  # PR이 main 브랜치에 병합될 때만 실행

jobs:
  build:
    if: github.event.pull_request.merged == true  # PR이 병합된 경우에만 빌드 실행
    runs-on: ubuntu-latest

    permissions:  # 권한 설정
      contents: write  # 리포지토리에 쓰기 권한을 부여

    steps:
      # 1. GitHub에서 리포지토리 체크아웃
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # 전체 Git 기록과 태그를 포함

      # 2. JDK 설치 (Android 앱을 빌드하기 위한 Java 설치)
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      # 3. gradlew 파일에 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # 4. GitHub Secrets에서 키스토어 로드 및 파일 생성
      - name: Generate Keystore file from Github Secrets
        run: |
          mkdir -p ./app/keystore
          echo "$KEYSTORE" > ./app/keystore/keystore.b64
          base64 -d ./app/keystore/keystore.b64 > ./app/keystore/MOUMkey2.jks
        env:
          KEYSTORE: ${{ secrets.APP_KEYSTORE_BASE64 }}

      # 5. 키스토어 파일 생성 확인
      - name: Verify Keystore File Path
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing files in ./app/keystore/"
          ls -l ./app/keystore/
          if [ ! -f ./app/keystore/MOUMkey2.jks ]; then
            echo "Keystore file is missing!"
            exit 1
          fi

      # 6. Gradle로 APK 빌드 (서명 포함)
      - name: Build APK with Signing
        run: ./gradlew assembleRelease --info
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      # 7. APK 서명 확인
      - name: Verify APK Signing
        run: jarsigner -verify -verbose -certs app/build/outputs/apk/release/app-release.apk

      # 8. APK 파일 경로 찾기
      - name: Find APK Path
        id: find_apk
        run: |
          APK_PATH=$(find app/build/outputs/apk/release/ -name "*.apk" | head -n 1)
          echo "APK path: $APK_PATH"
          echo ::set-output name=apk_path::$APK_PATH

      # 9. GitHub API를 통해 최신 태그 가져오기
      - name: Get latest tag
        id: get_tag
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1` || echo "v0.0.0")
          echo "Latest tag: $latest_tag"
          echo ::set-output name=latest_tag::$latest_tag

      # 10. 새 버전 태그 생성 (기존 태그에서 숫자를 증가시킴)
      - name: Bump version tag
        id: bump_version
        run: |
          latest_tag=${{ steps.get_tag.outputs.latest_tag }}
          IFS='.' read -r -a parts <<< "${latest_tag#v}"
          major="${parts[0]}"
          minor="${parts[1]}"
          patch="${parts[2]}"
          
          if [ "$patch" -eq 9 ]; then
            patch=0
            minor=$((minor+1))
          else
            patch=$((patch+1))
          fi

          if [ "$minor" -eq 10 ]; then
            minor=0
            major=$((major+1))
          fi

          new_tag="v$major.$minor.$patch"
          echo "New tag: $new_tag"
          echo ::set-output name=new_tag::$new_tag

      # 11. 새로운 태그를 원격 저장소에 푸시
      - name: Push new tag to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag ${{ steps.bump_version.outputs.new_tag }}
          git push origin ${{ steps.bump_version.outputs.new_tag }}

      # 12. GitHub Releases에 새 릴리스 생성 및 APK 업로드
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.bump_version.outputs.new_tag }}
          name: "MOUM-${{ steps.bump_version.outputs.new_tag }}"
          body: "음악인들을 잇는 커뮤니티 플랫폼 어플리케이션, MOUM:모音\n*app-release.apk 다운로드.\n\nNew release based on version ${{ steps.bump_version.outputs.new_tag }}."
          draft: false
          prerelease: false
          artifacts: ${{ steps.find_apk.outputs.apk_path }}  # APK 경로를 동적으로 설정
          replacesArtifacts: true  # 기존 파일 대체 설정
          skipIfReleaseExists: false  # 기존 릴리스가 있어도 무시하고 업데이트
