name: Test coverage

on:
  push:
    branches:
      - main
  pull_request:
      branches:
        - main   # main 브랜치에 pull_request를 보낼 때 실행

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # 1. GitHub에서 리포지토리 체크아웃
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # 전체 Git 기록과 태그를 포함

      # 2. JDK 설치 (Android 앱을 빌드하기 위한 Java 설치)
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      # 3. gradlew 파일에 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # 4.gradlew test 실행
      - name: Test with Gradle
        run: ./gradlew --info test

      # 5. jacocoTest Report 생성
      - name: Jacoco Report
        run: ./gradlew jacocoTestReport

      # 6. test 후 Report 생성
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: '**/build/test-results/testDebugUnitTest/TEST-*.xml'

      # 7. jacoco 커버리지 가져오기
      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.0
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/**/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "코드 커버리지 측정"
          min-coverage-overall: 0
          min-coverage-changed-files: 0